// Situation templates. Every template is written for the LEFT side of the field
// (ball on our left, x small). The generator mirrors them randomly, shifts them and
// varies pressure, so each template produces many different situations.
//
// Fields:
//   poss       'us' or 'them' (who has the ball)
//   ball       [xMin, xMax, yMin, yMax] area where the ball is
//   carriers   positions that can have the ball (our positions if poss=us,
//              opponent positions seen from THEIR side if poss=them;
//              their RA/RM play on our left side)
//   meHasBall  true: the player himself has the ball
//   me         positions this situation is meant for
//   ourBlock / oppBlock  shift of a team's shape (negative = higher up the field
//              in the direction that team attacks)
//   press      [min, max] how hard the defending team presses
//   meOffset   [min, max] meters the player starts away from his normal spot
//   special    extra layout rule
window.JO = window.JO || {};
JO.templates = [
  // ---------- Opbouwen ----------
  { id: 'k_uittrap_aanbieden', phase: 'opbouw', poss: 'us', ball: [16, 26, 58, 61], carriers: ['K'],
    me: ['LA', 'CV', 'RA', 'LM', 'CM', 'RM'], press: [0.1, 0.45], meOffset: [2, 6],
    title: 'Opbouwen vanaf de keeper',
    prompt: 'Onze keeper {carrier} heeft de bal. Waar ga jij staan zodat de keeper je kan aanspelen?' },
  { id: 'k_uittrap_druk', phase: 'opbouw', poss: 'us', ball: [16, 26, 58, 61], carriers: ['K'],
    me: ['LA', 'CV', 'RA', 'LM', 'CM', 'RM'], press: [0.65, 0.95], meOffset: [2, 5],
    title: 'Keeper onder druk',
    prompt: 'De tegenstander zet hoog druk. Keeper {carrier} heeft de bal. Waar ben jij aanspeelbaar?' },
  { id: 'k_kiest', phase: 'opbouw', poss: 'us', ball: [17, 25, 57, 61], carriers: ['K'], meHasBall: true,
    me: ['K'], press: [0.2, 0.9],
    title: 'Keeper aan de bal',
    prompt: 'Jij hebt de bal als keeper. Naar wie speel je hem?' },
  { id: 'cv_aan_bal', phase: 'opbouw', poss: 'us', ball: [12, 26, 44, 54], carriers: ['CV', 'LA'], meHasBall: true,
    me: ['CV', 'LA'], press: [0.2, 0.75],
    title: 'Verdediger aan de bal',
    prompt: 'Jij hebt de bal achterin. Wat doe je?' },
  { id: 'back_aan_bal_druk', phase: 'opbouw', poss: 'us', ball: [2, 8, 40, 52], carriers: ['LA'], meHasBall: true,
    me: ['LA'], press: [0.6, 0.95],
    title: 'Back onder druk',
    prompt: 'Je hebt de bal langs de zijlijn en een tegenstander komt op je af. Wat is de slimste keuze?' },
  { id: 'cv_steunen', phase: 'opbouw', poss: 'us', ball: [14, 28, 44, 52], carriers: ['CV'],
    me: ['LA', 'RA', 'LM', 'CM', 'RM', 'SP'], press: [0.2, 0.6], meOffset: [2, 6],
    title: 'Helpen bij de opbouw',
    prompt: '{carrier} heeft de bal achterin. Waar ga jij staan om te helpen?' },
  { id: 'back_steunen', phase: 'opbouw', poss: 'us', ball: [2, 8, 40, 52], carriers: ['LA'],
    me: ['LM', 'CM', 'CV', 'SP'], press: [0.4, 0.8], meOffset: [2, 6],
    title: 'Opbouw langs de zijkant',
    prompt: '{carrier} heeft de bal langs de zijlijn. Hoe help jij?' },
  { id: 'mid_aan_bal', phase: 'opbouw', poss: 'us', ball: [8, 26, 30, 42], carriers: ['CM', 'LM'], meHasBall: true,
    me: ['CM', 'LM'], press: [0.2, 0.8],
    title: 'Middenvelder aan de bal',
    prompt: 'Jij hebt de bal op het middenveld. Wat doe je?' },
  { id: 'mid_steunen', phase: 'opbouw', poss: 'us', ball: [16, 26, 32, 42], carriers: ['CM'],
    me: ['LM', 'RM', 'SP', 'CV', 'LA', 'RA'], press: [0.3, 0.7], meOffset: [2, 6],
    title: 'Aanspeelbaar zijn',
    prompt: '{carrier} heeft de bal op het middenveld. Waar ga jij staan?' },
  { id: 'kantelen', phase: 'opbouw', poss: 'us', ball: [3, 10, 28, 44], carriers: ['LM', 'LA'], meHasBall: true,
    me: ['LM', 'LA'], press: [0.5, 0.85], special: 'overload',
    title: 'Naar de andere kant',
    prompt: 'Bijna alle tegenstanders staan aan jouw kant. Wat doe je?' },
  { id: 'verre_kant', phase: 'opbouw', poss: 'us', ball: [3, 10, 28, 44], carriers: ['LM', 'LA'],
    me: ['RM', 'RA'], press: [0.5, 0.85], special: 'overload', meOffset: [3, 7],
    title: 'Ver van de bal',
    prompt: 'De bal is aan de andere kant bij {carrier}. Waar ga jij staan?' },

  // ---------- Aanvallen ----------
  { id: 'laatste_derde', phase: 'aanval', poss: 'us', ball: [8, 30, 15, 24], carriers: ['CM', 'LM', 'SP'], meHasBall: true,
    me: ['CM', 'LM', 'SP'], press: [0.3, 0.8],
    title: 'Vlak voor de zestien',
    prompt: 'Jij hebt de bal vlak voor de zestien van de tegenstander. Wat doe je?' },
  { id: 'schieten_of_passen', phase: 'aanval', poss: 'us', ball: [10, 30, 6, 14], carriers: ['SP', 'LM', 'CM'], meHasBall: true,
    me: ['SP', 'LM', 'CM'], press: [0.2, 0.8],
    title: 'Schieten of passen?',
    prompt: 'Jij hebt de bal in of bij de zestien. Schiet je, of geef je hem af?' },
  { id: 'diepte', phase: 'aanval', poss: 'us', ball: [8, 26, 28, 38], carriers: ['CM', 'LM'],
    me: ['SP', 'RM', 'LM'], oppBlock: -7, press: [0.2, 0.5], meOffset: [2, 5],
    title: 'Ruimte achter de verdediging',
    prompt: 'De verdedigers van de tegenstander staan hoog. {carrier} heeft de bal. Waar ga jij heen?' },
  { id: 'spits_vrijlopen', phase: 'aanval', poss: 'us', ball: [6, 34, 20, 32], carriers: ['LM', 'CM', 'RM'],
    me: ['SP'], press: [0.3, 0.7], meOffset: [3, 6],
    title: 'Vrijlopen als spits',
    prompt: '{carrier} heeft de bal. Hoe zorg jij dat je vrij staat?' },
  { id: 'aansluiten', phase: 'aanval', poss: 'us', ball: [14, 28, 14, 22], carriers: ['SP'],
    me: ['CM', 'LM', 'RM'], press: [0.5, 0.8], meOffset: [3, 6],
    title: 'Aansluiten bij de spits',
    prompt: 'Onze spits {carrier} heeft de bal met de rug naar het doel. Hoe help jij?' },
  { id: 'breed_houden', phase: 'aanval', poss: 'us', ball: [16, 26, 24, 36], carriers: ['CM'],
    me: ['LM', 'RM'], press: [0.3, 0.6], special: 'meInside', meOffset: [1, 3],
    title: 'Het veld groot maken',
    prompt: '{carrier} heeft de bal in het midden. Waar ga jij staan?' },
  { id: 'overlap', phase: 'aanval', poss: 'us', ball: [3, 9, 18, 30], carriers: ['LM'],
    me: ['LA'], press: [0.5, 0.8], meOffset: [1, 4],
    title: 'Mee naar voren',
    prompt: '{carrier} heeft de bal op de flank en wordt gedekt. Hoe help jij als back?' },
  { id: 'voorzet', phase: 'aanval', poss: 'us', ball: [2, 7, 4, 14], carriers: ['LM'], meHasBall: true,
    me: ['LM'], press: [0.3, 0.7],
    title: 'Bij de achterlijn',
    prompt: 'Jij bent bijna bij de achterlijn. Wat doe je met de bal?' },
  { id: 'voorzet_ontvangen', phase: 'aanval', poss: 'us', ball: [2, 7, 4, 14], carriers: ['LM', 'LA'],
    me: ['SP', 'CM', 'RM'], press: [0.3, 0.6], meOffset: [3, 6],
    title: 'In de zestien komen',
    prompt: '{carrier} kan de bal voorgeven. Waar ga jij staan?' },

  // ---------- Omschakelen: bal gewonnen ----------
  { id: 'counter_aan_bal', phase: 'balwinst', poss: 'us', ball: [8, 30, 36, 48], carriers: ['CM', 'CV', 'LM', 'LA'], meHasBall: true,
    me: ['CM', 'CV', 'LM', 'LA'], oppBlock: -14, press: [0.1, 0.4],
    title: 'Bal gewonnen!',
    prompt: 'We hebben net de bal gewonnen en de tegenstander staat nog ver naar voren. Wat doe je?' },
  { id: 'counter_meelopen', phase: 'balwinst', poss: 'us', ball: [8, 30, 38, 48], carriers: ['CM', 'CV', 'LA'],
    me: ['SP', 'LM', 'RM', 'CM'], oppBlock: -14, press: [0.1, 0.4], meOffset: [2, 5],
    title: 'Snel omschakelen',
    prompt: '{carrier} heeft de bal net veroverd. Waar ga jij heen?' },
  { id: 'keeper_snel', phase: 'balwinst', poss: 'us', ball: [17, 25, 58, 61], carriers: ['K'], meHasBall: true,
    me: ['K'], oppBlock: -16, press: [0.1, 0.3],
    title: 'Snel uitgooien',
    prompt: 'Je hebt de bal gevangen. De tegenstander staat nog voorin. Wat doe je?' },
  { id: 'twee_tegen_een', phase: 'balwinst', poss: 'us', ball: [10, 30, 20, 30], carriers: ['SP', 'LM', 'CM'], meHasBall: true,
    me: ['SP', 'LM', 'CM'], oppBlock: -16, press: [0.2, 0.5], special: 'fewback',
    title: 'Met z\'n tweeën tegen één',
    prompt: 'We breken uit en er staat bijna niemand meer achterin bij de tegenstander. Wat doe je?' },

  // ---------- Omschakelen: bal kwijt ----------
  { id: 'balverlies_druk', phase: 'balverlies', poss: 'them', ball: [8, 32, 24, 38], carriers: ['CM', 'RM', 'LM'],
    me: ['CM', 'LM', 'SP', 'RM'], ourBlock: -8, press: [0.2, 0.4], meOffset: [2, 5],
    title: 'Bal kwijt!',
    prompt: 'We zijn de bal net kwijtgeraakt. Wat doe jij?' },
  { id: 'balverlies_terug', phase: 'balverlies', poss: 'them', ball: [10, 32, 28, 40], carriers: ['CM', 'SP', 'RM'],
    me: ['LA', 'CV', 'RA', 'CM'], ourBlock: -14, press: [0.1, 0.3], meOffset: [2, 5],
    title: 'Terug naar achteren',
    prompt: 'We zijn de bal kwijt en de tegenstander gaat snel naar voren. Waar ga jij heen?' },
  { id: 'balverlies_spits', phase: 'balverlies', poss: 'them', ball: [10, 32, 10, 20], carriers: ['CV', 'LA', 'RA'],
    me: ['SP', 'LM', 'RM'], ourBlock: -4, press: [0.2, 0.5], meOffset: [2, 5],
    title: 'Meteen druk zetten',
    prompt: 'Hun verdediger heeft de bal net van ons afgepakt. Wat doe jij?' },

  // ---------- Verdedigen ----------
  { id: 'druk_op_bal', phase: 'verdedigen', poss: 'them', ball: [12, 30, 28, 38], carriers: ['CM'],
    me: ['CM', 'LM', 'RM', 'SP'], press: [0.3, 0.6], meOffset: [2, 5],
    title: 'Druk zetten',
    prompt: 'De tegenstander heeft de bal op het middenveld. Waar ga jij staan?' },
  { id: 'dekking_geven', phase: 'verdedigen', poss: 'them', ball: [3, 10, 36, 48], carriers: ['RM', 'RA'],
    me: ['CV', 'CM', 'LM', 'LA'], press: [0.6, 0.9], meOffset: [2, 5],
    title: 'Dekking geven',
    prompt: 'De tegenstander komt aan onze linkerkant. Waar ga jij staan?' },
  { id: 'compact', phase: 'verdedigen', poss: 'them', ball: [3, 10, 30, 46], carriers: ['RM', 'RA'],
    me: ['RA', 'RM', 'CM'], press: [0.4, 0.8], special: 'meWide', meOffset: [1, 3],
    title: 'Compact staan',
    prompt: 'De bal is aan de andere kant. Waar ga jij staan?' },
  { id: 'spits_dekken', phase: 'verdedigen', poss: 'them', ball: [10, 32, 32, 42], carriers: ['CM', 'LM', 'RM'],
    me: ['CV', 'LA', 'RA'], press: [0.3, 0.6], meOffset: [4, 8],
    title: 'Je tegenstander dekken',
    prompt: 'De tegenstander gaat aanvallen. Hoe dek jij jouw tegenstander?' },
  { id: 'hoge_druk', phase: 'verdedigen', poss: 'them', ball: [14, 28, 4, 10], carriers: ['K', 'CV'],
    me: ['SP', 'LM', 'RM', 'CM'], press: [0.3, 0.7], meOffset: [2, 6],
    title: 'Druk op hun opbouw',
    prompt: 'De tegenstander bouwt op vanaf achteren. Hoe zet jij druk?' },
  { id: 'eigen_zestien', phase: 'verdedigen', poss: 'them', ball: [6, 34, 44, 52], carriers: ['LM', 'RM', 'SP', 'CM'],
    me: ['CV', 'LA', 'RA', 'CM', 'LM', 'RM'], press: [0.4, 0.7], meOffset: [2, 5],
    title: 'Verdedigen bij ons doel',
    prompt: 'De tegenstander is vlak bij ons doel. Waar ga jij staan?' },
  { id: 'keeper_positie', phase: 'verdedigen', poss: 'them', ball: [6, 36, 44, 54], carriers: ['SP', 'CM', 'RM', 'LM'],
    me: ['K'], press: [0.2, 0.5], meOffset: [3, 6],
    title: 'Keeper: goed staan',
    prompt: 'Een tegenstander komt op ons doel af. Waar ga jij staan als keeper?' },

  // ---------- Spelhervattingen ----------
  { id: 'uitbal_voor', phase: 'hervatting', poss: 'us', ball: [0.3, 0.3, 24, 50], carriers: ['LA', 'LM'],
    me: ['LM', 'CM', 'SP', 'CV', 'LA'], press: [0.4, 0.8], special: 'sideline', meOffset: [2, 5],
    title: 'Uitbal voor ons',
    prompt: '{carrier} dribbelt de bal in. Waar ga jij staan zodat je daarna aanspeelbaar bent?' },
  { id: 'uitbal_zelf', phase: 'hervatting', poss: 'us', ball: [0.3, 0.3, 24, 50], carriers: ['LA', 'LM'], meHasBall: true,
    me: ['LA', 'LM'], press: [0.3, 0.8], special: 'sideline', onlyDribble: true,
    title: 'Jij dribbelt in',
    prompt: 'Uitbal voor ons. Jij dribbelt de bal in (passen mag niet). Waar dribbel je heen?' },
  { id: 'hoekschop_voor', phase: 'hervatting', poss: 'us', ball: [0.6, 0.6, 0.6, 0.6], carriers: ['LM', 'RM'],
    me: ['SP', 'CM', 'CV', 'RM', 'RA', 'LA'], special: 'corner_for', meOffset: [2, 5],
    title: 'Hoekschop voor ons',
    prompt: '{carrier} neemt de hoekschop (indribbelen, passen of schieten mag). Waar ga jij staan?' },
  { id: 'hoekschop_tegen', phase: 'hervatting', poss: 'them', ball: [0.6, 0.6, 63.4, 63.4], carriers: ['RM', 'LM'],
    me: ['K', 'LA', 'CV', 'RA', 'LM', 'CM', 'RM', 'SP'], special: 'corner_against', meOffset: [2, 5],
    title: 'Hoekschop tegen',
    prompt: 'De tegenstander neemt een hoekschop. Blijf 5 meter van de bal. Waar ga jij staan?' },
  { id: 'vrije_trap', phase: 'hervatting', poss: 'us', ball: [8, 32, 22, 40], carriers: ['CM', 'CV', 'LM'], meHasBall: true,
    me: ['CM', 'CV', 'LM'], press: [0.3, 0.6], special: 'freekick',
    title: 'Vrije bal',
    prompt: 'We hebben een vrije bal en jij neemt hem. Je mag dribbelen, passen of schieten. Wat doe je?' },
  { id: 'uitbal_tegen', phase: 'hervatting', poss: 'them', ball: [0.3, 0.3, 26, 50], carriers: ['RA', 'RM'],
    me: ['LA', 'LM', 'CM', 'CV'], press: [0.4, 0.7], special: 'sideline', meOffset: [2, 5],
    title: 'Uitbal tegen',
    prompt: 'De tegenstander dribbelt de bal in. Blijf 5 meter van de bal. Waar ga jij staan?' },
  { id: 'achterbal_tegen', phase: 'hervatting', poss: 'them', ball: [14, 28, 3, 8], carriers: ['K', 'CV'], special: 'restart',
    me: ['SP', 'LM', 'RM', 'CM'], press: [0.3, 0.6], meOffset: [3, 7],
    title: 'Achterbal tegen',
    prompt: 'De tegenstander neemt een achterbal. Wat is onze afspraak, en waar ga jij staan?' },
  { id: 'achterbal_voor', phase: 'hervatting', poss: 'us', ball: [14, 28, 56, 61], carriers: ['K', 'CV'], special: 'restart',
    me: ['LA', 'CV', 'RA', 'LM', 'CM', 'RM', 'SP'], press: [0.3, 0.7], meOffset: [2, 6],
    title: 'Achterbal voor ons',
    prompt: '{carrier} neemt de achterbal. Waar ga jij staan?' }
];

// Short lines about the match situation. risk: how bad losing the ball is,
// att: how much going forward is worth.
JO.contexts = [
  { text: 'Het staat 0-0.', risk: 1, att: 1 },
  { text: 'Het staat 0-0, eerste minuut van de wedstrijd.', risk: 1.1, att: 1 },
  { text: 'We staan 1-0 voor. Nog 2 minuten te spelen.', risk: 1.4, att: 0.9 },
  { text: 'We staan 0-1 achter. Nog 3 minuten te spelen.', risk: 0.8, att: 1.25 },
  { text: 'Het staat 2-2 in de tweede helft.', risk: 1, att: 1.05 },
  { text: 'We staan 3-1 voor.', risk: 1.2, att: 0.95 },
  { text: 'Het staat 1-1. Laatste minuut!', risk: 0.95, att: 1.15 },
  { text: 'We staan 1-2 achter in de eerste helft.', risk: 0.95, att: 1.1 }
];
